# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/eduardbostina/Desktop/01 Projects/matrix-lib-cpp"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/eduardbostina/Desktop/01 Projects/matrix-lib-cpp"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/eduardbostina/Desktop/01 Projects/matrix-lib-cpp/CMakeFiles" "/Users/eduardbostina/Desktop/01 Projects/matrix-lib-cpp//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/eduardbostina/Desktop/01 Projects/matrix-lib-cpp/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named matrix-test

# Build rule for target.
matrix-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix-test
.PHONY : matrix-test

# fast build rule for target.
matrix-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-test.dir/build.make CMakeFiles/matrix-test.dir/build
.PHONY : matrix-test/fast

#=============================================================================
# Target rules for targets named matrix-demo

# Build rule for target.
matrix-demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix-demo
.PHONY : matrix-demo

# fast build rule for target.
matrix-demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-demo.dir/build.make CMakeFiles/matrix-demo.dir/build
.PHONY : matrix-demo/fast

#=============================================================================
# Target rules for targets named matrix-benchmark

# Build rule for target.
matrix-benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 matrix-benchmark
.PHONY : matrix-benchmark

# fast build rule for target.
matrix-benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-benchmark.dir/build.make CMakeFiles/matrix-benchmark.dir/build
.PHONY : matrix-benchmark/fast

#=============================================================================
# Target rules for targets named simd-test

# Build rule for target.
simd-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simd-test
.PHONY : simd-test

# fast build rule for target.
simd-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simd-test.dir/build.make CMakeFiles/simd-test.dir/build
.PHONY : simd-test/fast

examples/benchmark.o: examples/benchmark.cpp.o
.PHONY : examples/benchmark.o

# target to build an object file
examples/benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-benchmark.dir/build.make CMakeFiles/matrix-benchmark.dir/examples/benchmark.cpp.o
.PHONY : examples/benchmark.cpp.o

examples/benchmark.i: examples/benchmark.cpp.i
.PHONY : examples/benchmark.i

# target to preprocess a source file
examples/benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-benchmark.dir/build.make CMakeFiles/matrix-benchmark.dir/examples/benchmark.cpp.i
.PHONY : examples/benchmark.cpp.i

examples/benchmark.s: examples/benchmark.cpp.s
.PHONY : examples/benchmark.s

# target to generate assembly for a file
examples/benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-benchmark.dir/build.make CMakeFiles/matrix-benchmark.dir/examples/benchmark.cpp.s
.PHONY : examples/benchmark.cpp.s

examples/demo.o: examples/demo.cpp.o
.PHONY : examples/demo.o

# target to build an object file
examples/demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-demo.dir/build.make CMakeFiles/matrix-demo.dir/examples/demo.cpp.o
.PHONY : examples/demo.cpp.o

examples/demo.i: examples/demo.cpp.i
.PHONY : examples/demo.i

# target to preprocess a source file
examples/demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-demo.dir/build.make CMakeFiles/matrix-demo.dir/examples/demo.cpp.i
.PHONY : examples/demo.cpp.i

examples/demo.s: examples/demo.cpp.s
.PHONY : examples/demo.s

# target to generate assembly for a file
examples/demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-demo.dir/build.make CMakeFiles/matrix-demo.dir/examples/demo.cpp.s
.PHONY : examples/demo.cpp.s

examples/simd_test.o: examples/simd_test.cpp.o
.PHONY : examples/simd_test.o

# target to build an object file
examples/simd_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simd-test.dir/build.make CMakeFiles/simd-test.dir/examples/simd_test.cpp.o
.PHONY : examples/simd_test.cpp.o

examples/simd_test.i: examples/simd_test.cpp.i
.PHONY : examples/simd_test.i

# target to preprocess a source file
examples/simd_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simd-test.dir/build.make CMakeFiles/simd-test.dir/examples/simd_test.cpp.i
.PHONY : examples/simd_test.cpp.i

examples/simd_test.s: examples/simd_test.cpp.s
.PHONY : examples/simd_test.s

# target to generate assembly for a file
examples/simd_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/simd-test.dir/build.make CMakeFiles/simd-test.dir/examples/simd_test.cpp.s
.PHONY : examples/simd_test.cpp.s

tests/main.o: tests/main.cpp.o
.PHONY : tests/main.o

# target to build an object file
tests/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-test.dir/build.make CMakeFiles/matrix-test.dir/tests/main.cpp.o
.PHONY : tests/main.cpp.o

tests/main.i: tests/main.cpp.i
.PHONY : tests/main.i

# target to preprocess a source file
tests/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-test.dir/build.make CMakeFiles/matrix-test.dir/tests/main.cpp.i
.PHONY : tests/main.cpp.i

tests/main.s: tests/main.cpp.s
.PHONY : tests/main.s

# target to generate assembly for a file
tests/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/matrix-test.dir/build.make CMakeFiles/matrix-test.dir/tests/main.cpp.s
.PHONY : tests/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... matrix-benchmark"
	@echo "... matrix-demo"
	@echo "... matrix-test"
	@echo "... simd-test"
	@echo "... examples/benchmark.o"
	@echo "... examples/benchmark.i"
	@echo "... examples/benchmark.s"
	@echo "... examples/demo.o"
	@echo "... examples/demo.i"
	@echo "... examples/demo.s"
	@echo "... examples/simd_test.o"
	@echo "... examples/simd_test.i"
	@echo "... examples/simd_test.s"
	@echo "... tests/main.o"
	@echo "... tests/main.i"
	@echo "... tests/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

